---
driver:
  name: vagrant

provisioner:
  name: puppet_apply
  manifests_path: examples
  hiera_data_path: hieradata
  ignore_spec_fixtures: true

transport:
  name: sftp

platforms:
  - name: centos-7.2

verifier:
  name: serverspec
  remote_exec: false
  extra_flags: '--require spec_helper -I spec/acceptance'

suites:
  - name: default
    provisioner:
      manifest: init.pp
    verifier:
      patterns:
        - 'spec/acceptance/**_spec.rb'
